# Generated by Django 2.2.6 on 2019-10-12 18:23

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='A unique identifier for the user.', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='A boolean indicating if the user account is active. Inactive accounts cannot perform actions on the site.', verbose_name='is active')),
                ('is_staff', models.BooleanField(default=False, help_text='A boolean indicating if the user is allowed to access the admin site.', verbose_name='is staff')),
                ('is_superuser', models.BooleanField(default=False, help_text='A boolean indicating if the user has all permissions without them being explicitly granted.', verbose_name='is superuser')),
                ('name', models.CharField(help_text="The user's name.", max_length=100, verbose_name='full name')),
                ('time_created', models.DateTimeField(auto_now_add=True, help_text='The time the user was created.', verbose_name='time created')),
                ('time_updated', models.DateTimeField(auto_now=True, help_text='The time the user was last updated.', verbose_name='time updated')),
                ('username', models.CharField(help_text='The name the user logs in as.', max_length=100, unique=True, verbose_name='username')),
                ('email', models.EmailField(help_text='email to contact user', max_length=200, unique=True, verbose_name='email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='phone number to which menu will be texted', max_length=128, region=None, unique=True, verbose_name='phone number')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('time_created',),
            },
        ),
    ]
