# Generated by Django 2.2.6 on 2019-10-12 19:20

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dietary', multiselectfield.db.fields.MultiSelectField(choices=[('prop-vegetarian', 1), ('prop-vegan', 2), ('prop-made_without_gluten', 3), ('allergen-has_egg', 4), ('allergen-has_soy', 5), ('allergen-has_wheat', 6), ('allergen-has_milk', 7), ('allergen-has_fish', 8), ('allergen-has_shellfish', 9), ('allergen-has_peanut', 10), ('allergen-has_tree_nuts', 11)], max_length=206)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('meal', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('menuItems', models.ManyToManyField(to='scraper.MenuItem')),
            ],
        ),
    ]
