# Generated by Django 2.2.6 on 2019-10-12 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Location'),
        ),
    ]
