# Generated by Django 2.2.6 on 2019-10-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20191012_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='meal',
            field=models.CharField(choices=[(1, 'Continental'), (2, 'Breakfast'), (3, 'Brunch'), (4, 'Lunch'), (5, 'Late Lunch'), (6, 'Midday'), (7, 'Dinner'), (8, 'Lite Dinner'), (9, 'Late Night')], max_length=50),
        ),
    ]
