# Generated by Django 2.2.6 on 2019-10-12 20:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20191012_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='dietary',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'prop-vegetarian'), (2, 'prop-vegan'), (3, 'prop-made_without_gluten'), (4, 'allergen-has_egg'), (5, 'allergen-has_soy'), (6, 'allergen-has_wheat'), (7, 'allergen-has_milk'), (8, 'allergen-has_fish'), (9, 'allergen-has_shellfish'), (10, 'allergen-has_peanut'), (11, 'allergen-has_tree_nuts')], max_length=23),
        ),
    ]
