# Generated by Django 2.2.6 on 2019-10-12 21:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20191012_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='dietary',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('prop-vegetarian', 'vegetarian'), ('prop-vegan', 'vegan'), ('prop-made_without_gluten', 'gluten free'), ('allergen-has_egg', 'has eggs'), ('allergen-has_soy', 'has soy'), ('allergen-has_wheat', 'has wheat'), ('allergen-has_milk', 'has milk'), ('allergen-has_fish', 'has fish'), ('allergen-has_shellfish', 'has shellfish'), ('allergen-has_peanut', 'has peanuts'), ('allergen-has_tree_nuts', 'has tree nuts')], max_length=206),
        ),
    ]
